### ISSUE TITLE
Remove "advertised" in dataset metadata settings

### ISSUE THREAD

**Issue by monimes** [gobiernodigitalmonterrey/geonode#4]
Given our organization's use of Geonode, the option "Destacado" (highlights) in the dataset metadata settings is not needed and its presence may even cause confusion among its users. That is why it may be preferable to remove it. 

<img width="1437" alt="Captura de pantalla 2024-04-22 a la(s) 6 26 21 p m" src="https://github.com/gobiernodigitalmonterrey/geonode/assets/107084064/909708bc-b0e6-4e58-b1d2-1c4f315cb86d">

@cesar-benjamin

**Comment by cesarbenjamindotnet** [comment]
La característica de anunciado si es necesaria, en todo caso su uso y alcances debe extenderse en la documentación, para evitar las confusiones que mencionas.

De hecho me gustaría saber cuales usuarios tienen esas confusiones? esta caracteristica solo está disponible para administradores. Cuales administradores tienen confusión al respecto?

Como decía, si hay dudas, favor de referir a la documentación oficial y reflejar esos puntos en nuestro manual.
